### ISSUE TITLE
Add description of the project.

### ISSUE THREAD

**Issue by caramelomartins** [caramelomartins/awesome-linters#29]
Add description of the project to the top of the file, as per sugestion:
- [ ] includes a succinct description of the project/theme at the top ([example](https://github.com/willempienaar/awesome-quantified-self)),
- [ ] has been checked for inconsistent formatting, spelling, and grammar:
	- Each link description starts with an uppercase character and ends with a period.
	- Drop all the `A` / `An` prefixes in the descriptions.
	- Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.

This will be used for #28.

**Comment by caramelomartins** [comment]
@mlcdf please, whenever you feel like you have fixed this issue, close the issue and let me know so I can delete those development branches. We shouldn't have several branches for one simple list.

It would be better to either use a fork or hold off on incomplete work - maybe editing it outside Github, in a normal editor?

**Comment by caramelomartins** [comment]
Hello @mlcdf any news on this? 

I'm working on #30 to try and get into master by New Year's Eve. :smile: 

Thanks!

**Comment by mlcdf** [comment]
Hey @caramelomartins!

Between work, school & personal side projects, I've been pretty busy lately, but I think I can have a first draft ready by the end of the week (I'll need feedback on this). 😉

**Comment by caramelomartins** [comment]
We all have a life @mlcdf! Don't worry. 😃 

Just let me know when you have something we can review.

**Comment by caramelomartins** [comment]
Close by #34.
