### ISSUE TITLE
missing Elixir-language linter

### ISSUE THREAD

**Issue by odyright** [caramelomartins/awesome-linters#42]
Hello... add a linter for "elixir-lang" 
**### ie:** 
1. [Dogma](https://github.com/lpil/dogma)
2. [Credo](https://github.com/rrrene/credo)
3. [elixir_linter](https://github.com/SophieDeBenedetto/elixir_linter)

**Comment by mlcdf** [comment]
Hello.

Feel free to submit a pull request to add Dogma and Credo. Regarding [elixir_linter](https://github.com/SophieDeBenedetto/elixir_linter), it doesn't really fit in this list.

**Comment by caramelomartins** [comment]
`credo` was added in https://github.com/caramelomartins/awesome-linters/commit/f97d1ca5ab255f0f2b133f6faab9eb8698aac2c9 and `dogma` has a notification noticed. I'm considering this issue closed, as of now.
