### ISSUE TITLE
GraphQL section for schema linters?

### ISSUE THREAD

**Issue by jdehaan** [caramelomartins/awesome-linters#55]
For example:

https://github.com/cjoudrey/graphql-schema-linter

**Comment by caramelomartins** [comment]
@jdehaan Seems like a good idea. Want to open a new MR?

**Comment by jdehaan** [comment]
@caramelomartins ok I'll open a PR soon for this purpose. I think I even identified a second tool.

**Comment by jdehaan** [comment]
I wanted to make 2 separate PRs but github put both commits automatically in the same PR... I force push again with one change only to comply to your contibution guidelines. I'll make another separate PR after the merge.
