### ISSUE TITLE
Add commitlint

### ISSUE THREAD

**Issue by igorshubovych** [caramelomartins/awesome-linters#58]
I would love to create PR for it, but I do not know which section to put it.

Probably **Git** or **Source Control**.

https://github.com/conventional-changelog/commitlint

**Comment by caramelomartins** [comment]
Hey,

I'm not familiar with `commitlint`, is it Git only or does it work with SVN also, for example?

Thanks!

**Comment by igorshubovych** [comment]
As I get it is currently about Git

**Comment by caramelomartins** [comment]
@igorshubovych I would say to go with `Git` as a header then. Would you like to make a pull request?

**Comment by caramelomartins** [comment]
Closed in https://github.com/caramelomartins/awesome-linters/pull/65.
