### ISSUE TITLE
Combine C/C++ sections

### ISSUE THREAD

**Issue by pocc** [caramelomartins/awesome-linters#59]
The linters are the same for all of them (oclint, uncrustify, cppcheck, clang-format, clang-tidy, etc.)

Thoughts?

**Comment by caramelomartins** [comment]
Hey,

I'm not immediately opposed to it but that raises the question of what would happen if one linting tool would be specific for only one of those languages? Would there be 3 sections: C, C++ and C/C++?

As it stands, for example, clang-tidy, on their homepage seem to indicate they are focused on C++:

> clang-tidy is a clang-based C++ “linter” tool. 

So, while I'm not immediately opposed, it might become confusing if we say clang-tidy is a C linter and then, on their homepage, they say it is a "clang-based C++ “linter” tool" (even if we know it works with C).

Does this make sense?

**Comment by pocc** [comment]
Just the one C/C++ section. DRY is relevant here.

From personal experience, clang-tidy works great as a C linter as well. If there is a linter that ONLY works on one or the other, I think it makes sense to separate them, but I do not know of a linter that fits this description.

If someone is actually confused and searches issues, this issue documents the question.

**Comment by caramelomartins** [comment]
@pocc Alright. Do you want to submit a merge request for that?

**Comment by pocc** [comment]
Done.

**Comment by pocc** [comment]
Dear reader from the future,

If you find a C or C++ linter that deserves to be on this list and has no functionality for the other languages, please reopen this issue.
