### ISSUE TITLE
Add pre-commit to project

### ISSUE THREAD

**Issue by pocc** [caramelomartins/awesome-linters#61]
[pre-commit](https://pre-commit.com) is a utility that runs before commits can be made. The use case here is to [prettier](https://github.com/prettier/prettier) to enforce markdown style. If there is interest, I'll make a PR with a `.pre-commit-config.yaml`, having run prettier over the README.md.

**Comment by caramelomartins** [comment]
@pocc Yeah, that's something that would be interesting.

**Comment by pocc** [comment]
Cool I've created a pre-commit config and run it against existing markdown files.

To run it, `pre-commit install` and a git pre-commit hook will be automatically created. It might be worth it to add this to the Contributing section.
